MODEL:
  name: "baseCNN"  # name of model
  patch_size: 7  
  removeZeroLabels: True
  weights: "./checkpoints/baseCNN/model.pth"

SOLVER:
  mode: "train"           # you can use args like "python main.py --mode train" to reset it. choices=["train", "test", "predict"]
  pca_components: 30      # channel after pre-processing, equal to input_channels
  HM_mixup: False         # whether to use mixup between Hyperspectral and Multispectral Image
  oversample: False       # whether to use oversample on weak class
  augmentData: True
  normalize: True
  batch_size: 256
  epochs: 200
  lr: 0.0001

OUTPUT_DIR: "./checkpoints/baseCNN"